import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error

# NASA dataset has no column names
columns = [
    'engine_id',
    'cycle',
    'op_setting_1',
    'op_setting_2',
    'op_setting_3'
]

# add sensor names
for i in range(1, 22):
    columns.append(f'sensor_{i}')

# read dataset
df = pd.read_csv(
    "train_FD001.txt",
    sep=r"\s+",
    header=None
)

# dataset sometimes contains extra empty columns
df = df.iloc[:, :26]

# assign names
df.columns = columns

print("Shape:")
print(df.shape)

print("\nFirst 5 rows:")
print(df.head())

print("\nStatistics:")
print(df.describe())
# find maximum cycle for every engine
max_cycles = df.groupby('engine_id')['cycle'].max()

# add maximum cycle back into dataframe
df['max_cycle'] = df['engine_id'].map(max_cycles)

# create Remaining Useful Life
df['RUL'] = df['max_cycle'] - df['cycle']

print("\nRUL Sample:")

print(
    df[
        ['engine_id',
         'cycle',
         'max_cycle',
         'RUL']
    ].head(20)
)

engine1 = df[df['engine_id'] == 1]

plt.figure(figsize=(10,5))

plt.plot(
    engine1['cycle'],
    engine1['sensor_2']
)

plt.xlabel("Cycle")
plt.ylabel("Sensor 2")
plt.title("Sensor 2 vs Engine Life")

plt.grid()

plt.show()
# input columns
features = [
    'op_setting_1',
    'op_setting_2',
    'op_setting_3'
]

for i in range(1, 22):
    features.append(f'sensor_{i}')

X = df[features]

y = df['RUL']
X_train, X_test, y_train, y_test = train_test_split(
    X,#questions or inputs ie features (sensor readings and op_settings )
    y,#answers or outputs ie the RUL values 
    test_size=0.2,#20% for testing and 80% for training 
    random_state=42#The split is already random. random_state fixes the random pattern so you get the same result every run.
)
#X_train:80% of sensor data
#X_test:20% of sensor data
#y_train:Actual RUL for training rows
#y_test:Actual RUL for testing rows
model = RandomForestRegressor(
    n_estimators=100,#"train 100 decision trees on different random subsets of the data and features and the forest combines the RUL generated by all trees and predicts final RUL as average
    random_state=42
)
model.fit(#model is trained - fit=train=learn
    X_train,
    y_train
)
predictions = model.predict(X_test)
mae = mean_absolute_error(
    y_test,
    predictions
)

print("\nMean Absolute Error:")
print(mae)
results = pd.DataFrame({
    'Actual_RUL': y_test.values,
    'Predicted_RUL': predictions
})

print("\nPrediction Sample:")
print(results.head(20))
feature_importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': model.feature_importances_
})

feature_importance = feature_importance.sort_values(
    by='Importance',
    ascending=False
)

print("\nTop Important Features:")
print(feature_importance.head(10))#tells us the 10 most important features which play a role in determining RUL
plt.figure(figsize=(10,6))

plt.bar(
    feature_importance['Feature'][:10],
    feature_importance['Importance'][:10]
)

plt.xticks(rotation=45)

plt.title("Top 10 Important Features")

plt.tight_layout()

plt.show()
print("\n========================")
print("MODEL COMPARISON")
print("========================")

# -----------------------------
# Random Forest
# -----------------------------

rf_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

rf_model.fit(
    X_train,
    y_train
)

rf_predictions = rf_model.predict(
    X_test
)

rf_mae = mean_absolute_error(
    y_test,
    rf_predictions
)

print("\nRandom Forest MAE:")
print(rf_mae)

# -----------------------------
# Extra Trees
# -----------------------------

et_model = ExtraTreesRegressor(
    n_estimators=100,
    random_state=42
)

et_model.fit(
    X_train,
    y_train
)

et_predictions = et_model.predict(
    X_test
)

et_mae = mean_absolute_error(
    y_test,
    et_predictions
)

print("\nExtra Trees MAE:")
print(et_mae)

# -----------------------------
# Gradient Boosting
# -----------------------------

gb_model = GradientBoostingRegressor(
    random_state=42
)

gb_model.fit(
    X_train,
    y_train
)

gb_predictions = gb_model.predict(
    X_test
)

gb_mae = mean_absolute_error(
    y_test,
    gb_predictions
)

print("\nGradient Boosting MAE:")
print(gb_mae)

# -----------------------------
# Best Model
# -----------------------------

mae_scores = {
    "Random Forest": rf_mae,
    "Extra Trees": et_mae,
    "Gradient Boosting": gb_mae
}

best_model = min(
    mae_scores,
    key=mae_scores.get
)

print("\n========================")
print("BEST MODEL")
print("========================")
print(best_model)
print("MAE =", mae_scores[best_model])

import joblib

joblib.dump(
    et_model,
    "best_engine_model.pkl"
)

print(
    "Best model saved successfully!"
)
